#!/bin/sh

logging_commence() {
	mkfifo "$prefix.tmp"
	tee "$prefix.log" <"$prefix.tmp" &
	set -v
	exec >"$prefix.tmp" 2>&1
}

logging_cleanup() {
	set +v
	rm "$prefix.tmp"
}

if [ $# -lt 1 ]
then
	cat <<-tac
		USAGE: $0 <command token>...

		Prepend $0 to the full command-line invokation of another script
		or program to log its environment, invocation, and interactions.

		If shell actions are provided (in escaped form so your own shell
		doesn't eat them, of course), they will be interpreted. To add
		files to the archive, place them in the \\\$dir directory.
	tac
	exit 127
fi

prefix="catbench-`basename $1`_`date +%F_%H-%M-%S_%z`"
if [ -e "$prefix.json" ]
then
	echo "ERROR: Output JSON file already exists; aborting!" >&2
	exit 127
fi

logging_commence

cp jaguar/template.json "$prefix.json"
jaguar/jaguar set "$prefix.json" meta.command "$*"
jaguar/jaguar set "$prefix.json" meta.commit "`git log --oneline --abbrev-commit --no-decorate -1`"
jaguar/jaguar set "$prefix.json" meta.date "`date "+%F %T %z"`"
jaguar/jaguar set "$prefix.json" meta.message "`git log --no-abbrev-commit --decorate -1`"
jaguar/jaguar set "$prefix.json" meta.patch "`git diff --ignore-submodules HEAD | base64`"
jaguar/jaguar set "$prefix.json" meta.status "`git status -uno`"
jaguar/jaguar set "$prefix.json" meta.submodule "`git submodule status`"
jaguar/jaguar set "$prefix.json" meta.uname "`uname -a`"

echo "$ $@"
eval "$@"
status="$?"

logging_cleanup
jaguar/jaguar set "$prefix.json" meta.log "`base64 "$prefix.log"`"
rm "$prefix.log"

exit "$status"
