#!/bin/sh

# hadoop_wrapper IN-DIR-PATH [[ITERS] HADOOP-OPTIONS]

input_dir_path=$1
outdir="hadoop_output/`cat /proc/sys/kernel/random/uuid`"
/home/doge/hadoop/bin/hadoop jar ~/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.3.jar wordcount $input_dir_path $outdir
rm -rf outdir
