#!/bin/sh

readonly CGROUP_PATH="/sys/fs/cgroup/intel_rdt"
readonly NUM_TRASH="7"
readonly TRASH_ALLOC="800"

if [ $# -ne 3 ]
then
	echo "USAGE: $0 <host on which to run client process> <path to repo on remote system> <mac address of local interface on which to listen>"
	exit 1
fi
foreign_client="$1"
remote_path="$2"
local_macaddr="$3"

logfilename="$CATBENCH_JAGFILE"
if [ -z "$logfilename" ]
then
	cat >&2 <<-tac
		$0: should be invoked via driver
	tac
	exit 1
fi

localrev="`git log --no-abbrev-commit -1 | head -n1 | cut -d' ' -f2`"
remoterev="`ssh "$foreign_client" "cd '$remote_path'; git log --no-abbrev-commit -1 | head -n1 | cut -d' ' -f2"`"
if [ "$localrev" != "$remoterev" ]
then
	echo "ERROR: Version mismatch between systems!" >&2
	exit 2
fi

remotemod="`ssh "$foreign_client" "cd '$remote_path'; git diff --exit-code HEAD >/dev/null; echo \\$?"`"
if [ "$remotemod" -ne 0 ]
then
	echo "ERROR: Remote repository state uncommitted!" >&2
	exit 3
fi

jaguar/jaguar set "$logfilename" legend.samples.table_entries.description string "Number of pointers to chase through"
jaguar/jaguar set "$logfilename" legend.samples.table_entries.unit string ""
jaguar/jaguar set "$logfilename" legend.samples.round_trip_time.description string "Round trip time from client perspective"
jaguar/jaguar set "$logfilename" legend.samples.round_trip_time.unit string "us"

setdefaultmask() {
	groupname="$1"
	groupmask="$2"

	sudo mkdir "$CGROUP_PATH/$groupname"
	sudo "sh -c 'echo $groupmask >$CGROUP_PATH/$groupname/intel_rdt.l3_cbm'"
	sudo "sh -c 'echo $$ >$CGROUP_PATH/$groupname/tasks'"
}

unsetmask() {
	sudo "sh -c 'echo $$ >$CGROUP_PATH/tasks'"
}

countfreepages() {
	sed -n 's/HugePages_Free:[[:space:]]\+\([[:digit:]]\)/\1/p' /proc/meminfo
}

waitforalloc() {
	# Wait for the number of free hugepages to drop.
	orig="`countfreepages`"
	while [ "`countfreepages`" -eq "$orig" ]; do :; done

	# Now wait for it to stabilize!
	while [ "`sed -n 's/HugePages_Free:[[:space:]]\+\([[:digit:]]\)/\1/p' /proc/meminfo`" -ne "$orig" ]
	do
		orig="`countfreepages`"
		sleep 1
	done
}

waitforexit() {
	arg0="$1"
	while (ps -eo args | cut -d" " -f1 | grep -x "$arg0" >/dev/null 2>&1); do :; done
}

runtrial() {
	res=""
	entries="$1"
	contenders="0"
	if [ -n "$2" ]
	then
		contenders="$2"
	fi
	mask="$3"

	if [ -n "$mask" ]
	then
		echo "NETWORK_RTT: Setting mask to $mask..."
		setdefaultmask lockserver "$mask"
	fi
	echo "NETWORK_RTT: Spawning server..."
	sudo clients/lockserver-ng -l "$entries" &
	waitforalloc

	if [ "$contenders" -ne 0 -a -n "$mask" ]
	then
		invmask="`printf '%#x\n' $((0xff - mask))`"
		echo "NETWORK_RTT: Setting mask to $invmask..."
		setdefaultmask trash "$invmask"
	fi
	for contender in `seq "$contenders"`
	do
		echo "NETWORK_RTT: Spawning contender $((contender - 1))"
		clients/square_evictions -c "$TRASH_ALLOC" -e "$TRASH_ALLOC" -hr >/dev/null &
	done

	if [ -n "$mask" ]
	then
		echo "NETWORK_RTT: Unsetting mask..."
		unsetmask
	fi
	echo "NETWORK_RTT: Spawning client..."
	echo "No need to enter your password at this prompt!"
	res="`ssh "$foreign_client" "echo '$passwd' | sudo -S '$remote_path/clients/lockclient' -m '$local_macaddr'"`"
	echo
	echo "$res" | sed -e '/^EAL: /d' -e 's/^/remote: /'

	echo "NETWORK_RTT: Cleaning up..."
	killall square_evictions
	sudo killall lockserver-ng
	waitforexit clients/lockserver-ng
	if [ -n "$mask" ]
	then
		cgdelete intel_rdt:lockserver
		cgdelete intel_rdt:trash
	fi
}

recordtrial() {
	var="$1"
	shift

	runtrial "$@" # populate res
	num="`echo "$res" | grep "Average:" | cut -d" " -f2`"
	eval $var="\$$var\\\\n\$table_entries,\$num"
}

echo -n "Remote sudo password? "
stty -echo
read passwd
stty echo
echo

header="integer,fraction\ntable_entries,trip_time"
jaguar/jaguar set "$logfilename" data.baseline.description string "Baseline"
jaguar/jaguar set "$logfilename" data.contention.description string "Contention"
baseline="$header"
contention="$header"
sudo -l >/dev/null
for table_entries in 1 10 100 1000 10000
do
	cat <<-tac

		RUNNING ITERATION: $table_entries

	tac
	recordtrial baseline "$table_entries"
	recordtrial contention "$table_entries" "$NUM_TRASH"
done
echo "$baseline" | jaguar/jaguar set "$logfilename" data.baseline.samples array -
echo "$contention" | jaguar/jaguar set "$logfilename" data.contention.samples array -
