#!/bin/sh

# Pseudo-modifier for variable declarations.
# Creates a constant with the specified default value, unless a specialization is found in the environment.
const() {
	local varname="`printf %s "$1" | cut -d= -f1`"
	local vardef="`printf %s "$1" | cut -d= -f2-`"
	if eval [ -z '"$'"$varname"'"' ]
	then
		eval "$varname"='"'"$vardef"'"'
	fi
	eval readonly "$varname"
}

const NUM_ITERATIONS="30000000"
const NUM_WARMUP="10000000"
const DEFAULT_CLIENT_SLEEP="100000"
const DEFAULT_CLIENT_SLEEP_LOOP="0 10 100 1000 10000 100000"
const DEFAULT_ZIPF_ALPHA="0.99"
const DEFAULT_ZIPF_ALPHA_LOOP="0.00 0.90 0.99"
const DEFAULT_CACHE_WAYS="0x00f"
const DEFAULT_CACHE_WAYS_LOOP="0x001 0x003 0x007 0x00f 0x01f 0x03f 0x07f 0x0ff 0x1ff 0x3ff 0x7ff 0xfff"
const DEFAULT_MITE_TPUT_LIMIT="3.0"
const DEFAULT_MITE_TPUT_LIMIT_LOOP="0.2 0.4 0.6 0.8 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0 3.2 3.4 3.6 3.8 4.0"

const CGROUP_PATH="/sys/fs/cgroup/intel_rdt"
const MICA_GET_RATIO="0.5"
const MICA_NUM_ITEMS="131072"
const NUM_TRASH="7"
const PERF_CORES="0"
const TRASH_ALLOC="800"

usage() {
	cat <<-tac
		USAGE: $0 <-s|-t|-m|-c> <host on which to run client process> <path to repo on remote system>

		-s: Vary sleep and fix zipf alpha at $DEFAULT_ZIPF_ALPHA
		-t: Vary zipf alpha and fix the sleep at $DEFAULT_CLIENT_SLEEP s
		-m: Vary the number of ways allocated to the mite
		-c: Vary the number of ways allocated to Trash
		-l: Vary the mite throughput limit
	tac
}

client_sleep="$DEFAULT_CLIENT_SLEEP"
zipf_alpha="$DEFAULT_ZIPF_ALPHA"
cache_ways="$DEFAULT_CACHE_WAYS"
cache_partition_mite="true"
mite_tput_limit="$DEFAULT_MITE_TPUT_LIMIT"
understood="true"
while "$understood"
do
	case "$1"
	in
		-s)
			independent="client_sleep"
			iterator="$DEFAULT_CLIENT_SLEEP_LOOP"
			;;
		-t)
			independent="zipf_alpha"
			iterator="$DEFAULT_ZIPF_ALPHA_LOOP"
			;;
		-m)
			independent="cache_ways"
			iterator="$DEFAULT_CACHE_WAYS_LOOP"
			;;
		-c)
			cache_partition_mite="false"
			independent="cache_ways"
			iterator="$DEFAULT_CACHE_WAYS_LOOP"
			;;
		-l)
			independent="mite_tput_limit"
			iterator="$DEFAULT_MITE_TPUT_LIMIT_LOOP"
			;;
		*)
			understood="false"
			;;
	esac

	if "$understood"
	then
		shift
	fi
done
if [ -z "$independent" -o $# -ne 2 ]
then
	usage
	exit 1
fi
foreign_client="$1"
remote_path="$2"

logfilename="$CATBENCH_JAGFILE"
if [ -z "$logfilename" ]
then
	cat >&2 <<-tac
		$0: should be invoked via driver
	tac
	exit 1
fi

localrev="`git log --no-abbrev-commit --no-decorate -1 | head -n1 | cut -d' ' -f2`"
remoterev="`ssh "$foreign_client" "cd '$remote_path'; git log --no-abbrev-commit --no-decorate -1 | head -n1 | cut -d' ' -f2"`"
#if [ "$localrev" != "$remoterev" ]
#then
	#echo "ERROR: Version mismatch between systems!" >&2
	#exit 2
#fi

remotemod="`ssh "$foreign_client" "cd '$remote_path'; git diff --exit-code HEAD >/dev/null; echo \\$?"`"
if [ "$remotemod" -ne 0 ]
then
	echo "ERROR: Remote repository state uncommitted!" >&2
	exit 3
fi

sudo killall server 2>/dev/null
sudo killall square_evictions 2>/dev/null

if [ "$independent" = "client_sleep" ]
then
	jaguar/jaguar set "$logfilename" legend.samples.client_sleep.description string "Delay between client requests"
	jaguar/jaguar set "$logfilename" legend.samples.client_sleep.unit string "us"
elif [ "$independent" = "zipf_alpha" ]
then
	jaguar/jaguar set "$logfilename" legend.samples.zipf_alpha.description string "Alpha parameter of zipf distribution"
	jaguar/jaguar set "$logfilename" legend.samples.zipf_alpha.unit string ""
elif [ "$independent" = "cache_ways" ]
then
	if "$cache_partition_mite"
	then
		way_description="#ways allocated exclusively to the mite"
	else
		way_description="#ways allocated to contenders (shared with mite)"
	fi
	jaguar/jaguar set "$logfilename" legend.samples.cache_ways.description string "$way_description"
	jaguar/jaguar set "$logfilename" legend.samples.cache_ways.unit string ""
	unset way_description
elif [ "$independent" = "mite_tput_limit" ]
then
	jaguar/jaguar set "$logfilename" legend.samples.mite_tput_limit.description string "Mite throughput limit"
	jaguar/jaguar set "$logfilename" legend.samples.mite_tput_limit.unit string "mops"
else
	echo "Internal ERROR, invalid independent variable. (Perhaps you forgot to add a jaguar entry for this independent variable?" >&2
	exit 4
fi
jaguar/jaguar set "$logfilename" legend.samples.mica_throughput.description string "Mica Throughput"
jaguar/jaguar set "$logfilename" legend.samples.mica_throughput.unit string "mops"

jaguar/jaguar set "$logfilename" legend.samples.mean.description string "Mean RTT"
jaguar/jaguar set "$logfilename" legend.samples.mean.unit string "us"

jaguar/jaguar set "$logfilename" legend.samples.999_tail_latency.description string "99.9th percentile tail RTT"
jaguar/jaguar set "$logfilename" legend.samples.999_tail_latency.unit string "us"

jaguar/jaguar set "$logfilename" legend.samples.99_tail_latency.description string "99th percentile tail RTT"
jaguar/jaguar set "$logfilename" legend.samples.99_tail_latency.unit string "us"

jaguar/jaguar set "$logfilename" legend.samples.95_tail_latency.description string "95th percentile tail RTT"
jaguar/jaguar set "$logfilename" legend.samples.95_tail_latency.unit string "us"
jaguar/jaguar set "$logfilename" legend.samples.perf_data.description string "Perf datafile"
jaguar/jaguar set "$logfilename" legend.samples.perf_data.unit string "all ur base64s are belong to me"
base64 -w0 ../mica2-catbench/build/server | jaguar/jaguar set "$logfilename" meta.server_binary string -

setdefaultmask() {
	groupname="$1"
	groupmask="$2"

	sudo mkdir "$CGROUP_PATH/$groupname"
	sudo sh -c "echo '$groupmask' >'$CGROUP_PATH/$groupname/intel_rdt.l3_cbm'"
	sudo sh -c "echo $$ >'$CGROUP_PATH/$groupname/tasks'"
}

unsetmask() {
	sudo sh -c "echo $$ >'$CGROUP_PATH/tasks'"
}

countfreepages() {
	sed -n 's/HugePages_Free:[[:space:]]\+\([[:digit:]]\)/\1/p' /proc/meminfo
}

waitforalloc() {
	numpages="$1"
	# Wait for the number of free hugepages to drop.
	orig="`countfreepages`"
	while [ "`countfreepages`" -eq "$orig" -a "$orig" -ne "$numpages" ]; do :; done

	# Now wait for it to stabilize!
	while [ "`sed -n 's/HugePages_Free:[[:space:]]\+\([[:digit:]]\)/\1/p' /proc/meminfo`" -ne "$orig" ]
	do
		orig="`countfreepages`"
		sleep 1
	done
}

waitforexit() {
	arg0="$1"
	while (ps -eo args | cut -d" " -f1 | grep -x "$arg0" >/dev/null 2>&1); do :; done
}

runtrial() {
	alpha="$1"
	contenders="0"
	if [ -n "$2" ]
	then
		contenders="$2"
	fi
	mask="$3"
	tlim="$4"

	if [ -n "$mask" ] && "$cache_partition_mite"
	then
		echo "NETWORK_RTT: Setting mask to $mask..."
		setdefaultmask lockserver "$mask"
	fi
	echo "NETWORK_RTT: Spawning server..."
	../mica2-catbench/script/setup.sh 16384 0
	( cd ../mica2-catbench/build && sudo ./server >../../catbench/rtt_server ) &
	waitforalloc 1024
	sleep 3

	if [ "$contenders" -ne 0 -a -n "$mask" ]
	then
		if "$cache_partition_mite"
		then
			trashmask="`printf '%#x\n' $((0xfffff - mask))`"
		else
			trashmask="$mask"
		fi
		echo "NETWORK_RTT: Setting mask to $trashmask..."
		setdefaultmask trash "$trashmask"
		unset trashmask
	fi
	for contender in `seq "$contenders"`
	do
		echo "NETWORK_RTT: Spawning contender $((contender - 1))"
		taskset "`printf '%#x' $((1 << ($(grep -m2 "physical id" /proc/cpuinfo | uniq | wc -l) * contender)))`" clients/square_evictions -c "$TRASH_ALLOC" -e "$TRASH_ALLOC" -uhr >/dev/null &
	done

	if [ -n "$mask" ]
	then
		echo "NETWORK_RTT: Unsetting mask..."
		unsetmask
	fi
	if [ "$independent" = "mite_tput_limit" ]
	then
		num_iter=`perl -e "print int($NUM_ITERATIONS * $tlim / 3)"`
		num_warm=`perl -e "print int($num_iter / 3)"`
	else
		num_iter=$NUM_ITERATIONS
		num_warm=$NUM_WARMUP
	fi
	while ! grep '^tput' rtt_server >/dev/null 2>&1; do sleep 1; done
	./onmycommand ./cacheperf "$PERF_CORES" >rtt_perf_duration &
	echo "NETWORK_RTT: Spawning client..."
	echo "No need to enter your password at this prompt!"
	ssh "$foreign_client" "cd '$remote_path'; rm -f rtt_client rtt_latencies; cd '../mica2-catbench/build' && echo '$passwd' | sudo -S ./netbench -n "$num_iter" -w "$num_warm" -o '../../$remote_path/rtt_latencies' -p '$MICA_NUM_ITEMS' '$MICA_GET_RATIO' '$alpha' '$tlim' | tee '../../$remote_path/rtt_client' | grep -F --line-buffered 'tput='" | ( grep -Fm1 "tput=" && killall -USR1 onmycommand && cat ) >/dev/null
	./cacheperf end >rtt_perf
	killall onmycommand
	sudo killall server
	waitforexit ./server
	#cat rtt_server >>"$CATBENCH_LOGFILE"

	echo "NETWORK_RTT: Cleaning up..."
	killall square_evictions
	if [ -n "$mask" ]
	then
		sudo cgdelete intel_rdt:lockserver
		sudo cgdelete intel_rdt:trash
	fi
	scp -C "$foreign_client:$remote_path/rtt_client" "$foreign_client:$remote_path/rtt_latencies" .
	sed 's/^/remote: /' rtt_client >>"$CATBENCH_LOGFILE"
	cat rtt_perf_duration >>"$CATBENCH_LOGFILE"
	cat rtt_perf >>"$CATBENCH_LOGFILE"
}

recordtrial() {
	var="$1"
	shift

	runtrial "$@"
	success="`grep "success_rate=" rtt_client | tail -n2 | head -n1 | cut -d"=" -f3 | perl -nle 'print $1 if /\s+(\S+)%/'`"
	tput="`grep "tput=" rtt_client | tail -n2 | head -n1 | cut -d"=" -f2 | perl -nle 'print $1 if /(\S+) Mops/'`"
	avg="`grep "Average:" rtt_client | cut -d" " -f2`"
	rtt_999="`grep "99.9-th" rtt_client | cut -d" " -f2`"
	rtt_99="`grep "99-th" rtt_client | cut -d" " -f2`"
	rtt_95="`grep "95-th" rtt_client | cut -d" " -f2`"
	if [ -z "$header" ]
	then
		if [ "$independent" = "cache_ways" ]
		then
			header="string"
		else
			header="fraction"
		fi
		header="$header,fraction,fraction,fraction,fraction,fraction,string,`cut -f1 rtt_perf | sed "s/.*/fraction/" | paste -sd,`\n$independent,mica_throughput,mean,999tail-latency,99tail-latency,95tail-latency,perf_data,`tr "\t" " " <rtt_perf | cut -d" " -f1 | tr "." "/" | paste -sd,`"
		baseline="$header"
		basealloc="$header"
		contention="$header"
		allocation="$header"
	fi

	total_time="`grep -F "seconds time elapsed" rtt_perf_duration | tr -s " " | cut -d" " -f2`"
	eval $var="\$$var\\\\n\$$independent,\$tput,\$avg,\$rtt_999,\$rtt_99,\$rtt_95,'`base64 -w0 perf.data`',`cut -f2 rtt_perf | tr -d "," | sed "s:\$:/$total_time:" | bc -l | paste -sd,`"
	echo "============================================="
	echo $success
	echo $tput
	echo $avg
	echo $rtt_999
	echo $rtt_99
	echo $rtt_95
	echo "============================================="
}

estimatetotal() {
	start_time="$1"
	trial_index="$2"
	trial_count="$3"
	current_time="$(date +%s)"
	echo "$(((current_time - start_time) * trial_count / trial_index))"
}

estimateremaining() {
	start_time="$1"
	trial_index="$2"
	trial_count="$3"
	current_time="$(date +%s)"
	echo "$(((current_time - start_time) * (trial_count - trial_index) / trial_index))"
}

formattime() {
	t="$1"
	s="$((t % 60))"
	m="$((t / 60 % 60))"
	h="$((t / 3600))"
	printf "%d:%02d:%02d" "$h" "$m" "$s"
}

printprogress() {
	start_time="$1"
	trial_index="$2"
	trial_count="$3"

	printf "(%d/%d) " "$trial_index" "$trial_count"

	t="`estimatetotal "$@"`"
	formattime "$t"
	echo -n " total; "

	t="`estimateremaining "$@"`"
	formattime "$t"
	echo " left"
}

#echo -n "Remote sudo password? "
#stty -echo
#read passwd
#stty echo
#echo
passwd="hunter2"

header=""

jaguar/jaguar set "$logfilename" data.baseline.description string "Baseline"
jaguar/jaguar set "$logfilename" data.basealloc.description string "Basealloc"
jaguar/jaguar set "$logfilename" data.contention.description string "Contention"
jaguar/jaguar set "$logfilename" data.allocation.description string "Allocation"

start_time="$(date +%s)"
trial_index=0
iteration_count=0; for input in $iterator; do iteration_count="$((iteration_count + 1))"; done
trial_count="$((iteration_count * 4))"

sudo -l >/dev/null
for input in $iterator
do
	eval $independent=$input
	eval cat <<-tac

		=================

		RUNNING ITERATION: $input

	tac
	recordtrial baseline "$zipf_alpha" 0 "" "$mite_tput_limit"
	trial_index=$((trial_index + 1)); printprogress "$start_time" "$trial_index" "$trial_count"
	eval cat <<-tac

		RUNNING TRIAL: $input basealloc

	tac
	recordtrial basealloc "$zipf_alpha" 0 "$cache_ways" "$mite_tput_limit"
	trial_index=$((trial_index + 1)); printprogress "$start_time" "$trial_index" "$trial_count"
	eval cat <<-tac

		RUNNING TRIAL: $input contention

	tac
	recordtrial contention "$zipf_alpha" "$NUM_TRASH" "" "$mite_tput_limit"
	trial_index=$((trial_index + 1)); printprogress "$start_time" "$trial_index" "$trial_count"
	eval cat <<-tac

		RUNNING TRIAL: $input allocation

	tac
	recordtrial allocation "$zipf_alpha" "$NUM_TRASH" "$cache_ways" "$mite_tput_limit"
	trial_index=$((trial_index + 1)); printprogress "$start_time" "$trial_index" "$trial_count"
done
echo "$baseline" | jaguar/jaguar set "$logfilename" data.baseline.samples array -
echo "$basealloc" | jaguar/jaguar set "$logfilename" data.basealloc.samples array -
echo "$contention" | jaguar/jaguar set "$logfilename" data.contention.samples array -
echo "$allocation" | jaguar/jaguar set "$logfilename" data.allocation.samples array -
ssh "$foreign_client" rm -f "$remote_path/rtt_client"
rm rtt_client
rm rtt_server
rm rtt_latencies
rm rtt_perf_duration
rm rtt_perf
