#!/bin/sh

logfile=""
core=""
mask=""

runtrial() {
	if [ -n "$tool" ]
	then
		runlog sudo sh -c PATH="$PATH" pcm.x -- taskset "$mask" ./square_evictions "$@"
	else
		runlog perf stat -e cache-misses,cache-references taskset "$mask" ./square_evictions "$@"
	fi
}

runlog() {
	echo "\$ $@"
	"$@"
}

if [ $# -lt 2 -o \( $# -ge 3 -a "$3" != "pcm" \) ]
then
	echo "USAGE: $0 <log file> <0xmask> [pcm]"
	exit 1
fi

logfile="$1"
mask="$2"
tool="$3"
exec >"$logfile" 2>&1
git log --oneline -1
git status -uno
git diff HEAD
echo ===
echo

seq 0 20 200 | while read ce
do
	runtrial -n1 -c"$ce" -e"$ce"
done
