#!/bin/sh

. ./summarize_helpers.sh

if [ $# -lt 2 -o \( $# -ge 3 -a "$3" != "pcm" \) ]
then
	echo "USAGE: $0 <log file> <0xmask> [pcm]"
	exit 1
fi

logfile="$1"
mask="$2"
tool="$3"

driver_init square_evictions "$logfile"
logstatus

seq 20 20 200 | while read ce
do
	runtrial "$mask" ./square_evictions -n1 -c"$ce" -e"$ce" -hr
done
