#!/bin/sh

. ./summarize_helpers.sh

if [ $# -lt 1 ]
then
	echo "USAGE: $0 <log file>"
	exit 1
fi

logfile="$1"
tool="pcm"

truncate -s0 "${logfile}_a"
truncate -s0 "${logfile}_b"

driver_init square_evictions "$logfile"
sudo ../external/pqos/pqos -e "llc:0=0xffc;llc:1=0x1;llc:2=0x2"
sudo ../external/pqos/pqos -a "llc:1=0,1;llc:2=2"
logstatus

runlog taskset 0x1 ./square_evictions -n1 -c55 -e55 -r &

toolargs="0.001 -csv=\"${logfile}_a\" -yc=1 -ns -nsys -m"
runtrial 0x2 ./square_evictions -n1 -c55 -e55 -r \&

toolargs="0.001 -csv=\"${logfile}_b\" -yc=2 -ns -nsys -m"
runtrial 0x4 ./square_evictions -n1 -c55 -e55 -r \&

sleep 20

runlog date +"%F;%T.%3N"
runlog sudo ../external/pqos/pqos -a "llc:2=0"
runlog date +"%F;%T.%3N"

wait %%
