#!/bin/sh

set -ev
sudo modprobe msr
sudo sh -c 'echo 0 >/proc/sys/kernel/perf_event_paranoid'
sudo sh -c 'echo 0 >/proc/sys/kernel/nmi_watchdog'
sudo sh -c 'echo 16384 >/proc/sys/vm/nr_hugepages'
sudo sh -c 'for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance >"$gov"; done'
echo "1" | sudo tee /sys/devices/system/cpu/cpu32/online

sudo sh -c 'echo never >/sys/kernel/mm/transparent_hugepage/enabled'
sudo sh -c 'echo never >/sys/kernel/mm/transparent_hugepage/defrag'

[ -e /sys/fs/cgroup/intel_rdt ] || sudo mount -t resctrl none /sys/fs/resctrl

#cd ~/hangups/examples
#nohup ./dogbert &
